networks:
  rc-chat:

volumes:
  postgres_data:
  redis_data:
  backend_public:
  backend_private:
  ngx_vhost:
  ngx_html:
  ngx_dhparam:
  ngx_certs:
  ngx_acme:

services:
  #-- Ambiente Local --#
  backend:
    profiles: ["local", "acme", "cloudflare"]
    image: ${IMAGE_PREFIX:-ghcr.io/rodadecuia}/rc-chat-backend:${IMAGE_TAG:-latest}
    volumes:
      - backend_public:/usr/src/app/public
      - backend_private:/usr/src/app/private
    env_file:
      - .env
    # Impede que o nginx-proxy detecte este container
    environment:
      - VIRTUAL_HOST=
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "${BACKEND_PORT:-8080}:3000"
    networks:
      - rc-chat

  frontend:
    profiles: ["local", "acme", "cloudflare"]
    image: ${IMAGE_PREFIX:-ghcr.io/rodadecuia}/rc-chat-frontend:${IMAGE_TAG:-latest}
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${FRONTEND_HOST}
      - LETSENCRYPT_HOST=${FRONTEND_HOST}
      - LETSENCRYPT_EMAIL=${EMAIL_ADDRESS}
    volumes:
      - backend_public:/var/www/backend-public
    restart: always
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    networks:
      - rc-chat

  #-- Ambiente de Desenvolvimento --#
  pgadmin4:
    profiles: ["dev"]
    image: dpage/pgadmin4:8
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@rc-chat.host
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "8081:80"
    volumes:
      - ${COMPOSE_PROJECT_PATH:-.}/confs/pgadmin4-servers.json:/pgadmin4/servers.json
    networks:
      - rc-chat

  #-- Ambiente de Produção (ACME) --#
  nginx-proxy:
    profiles: ["acme"]
    image: nginxproxy/nginx-proxy
    container_name: rc-chat-nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${COMPOSE_PROJECT_PATH:-.}/confs:/etc/nginx/conf.d
      - ngx_vhost:/etc/nginx/vhost.d
      - ngx_html:/usr/share/nginx/html
      - ngx_dhparam:/etc/nginx/dhparam
      - ngx_certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - rc-chat

  acme-companion:
    profiles: ["acme"]
    image: nginxproxy/acme-companion
    container_name: rc-chat-acme-companion
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - ngx_vhost:/etc/nginx/vhost.d
      - ngx_html:/usr/share/nginx/html
      - ngx_dhparam:/etc/nginx/dhparam:ro
      - ngx_certs:/etc/nginx/certs
      - ngx_acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=rc-chat-nginx-proxy
    networks:
      - rc-chat

  #-- Ambiente Cloudflare --#
  cloudflared:
    profiles: ["cloudflare"]
    image: cloudflare/cloudflared
    restart: always
    command: tunnel run
    env_file:
      - .env
    depends_on:
      - backend
      - frontend
    networks:
      - rc-chat

  #-- Serviços Comuns --#
  postgres:
    profiles: ["local", "dev", "acme", "cloudflare"]
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    expose:
      - 5432
    restart: always
    networks:
      - rc-chat

  redis:
    profiles: ["local", "dev", "acme", "cloudflare"]
    image: redis:alpine
    command: redis-server --appendonly yes
    expose:
      - 6379
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - rc-chat

  sidekick:
    profiles: ["local", "acme"]
    image: ghcr.io/ticketz-oss/ticketz-sidekick:latest
    env_file:
      - .env
    command: ${SIDEKICK_COMMAND}
    restart: unless-stopped
    volumes:
      - backend_public:/backend-public
      - backend_private:/backend-private
      - ${COMPOSE_PROJECT_PATH:-.}/backups:/backups
      - ${COMPOSE_PROJECT_PATH:-.}/retrieve:/retrieve
    depends_on:
      - postgres
    networks:
      - rc-chat
