name: Create and publish multi-arch Docker images

on:
  push:
    branches:
      - 'main'
      - 'beta'
      - 'fix/**'
      - 'dev'
      - 'test-**'
    tags:
      - 'v*.*.*'
env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ${{ github.repository_owner }}/rc-chat-backend
  IMAGE_FRONTEND: ${{ github.repository_owner }}/rc-chat-frontend
  DOCKERHUB_IMAGE_BACKEND: ${{ secrets.DOCKERHUB_USERNAME }}/rc-chat-backend
  DOCKERHUB_IMAGE_FRONTEND: ${{ secrets.DOCKERHUB_USERNAME }}/rc-chat-frontend

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get git info and setup version files
        run: |
          cat <<EOT > backend/src/gitinfo.ts
          export const GitInfo = {
              commitHash: "$(git rev-parse --short HEAD)",
              commitTimestamp: "$(date -u -d "$(git log -1 --format=%cI)" +'%Y-%m-%dT%H:%M:%SZ')",
              branchName: "$(git rev-parse --abbrev-ref HEAD)",
              tagName: "$(git describe --tags --abbrev=0 2>/dev/null)",
              buildTimestamp: "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          };
          EOT
          cat <<EOT > frontend/public/gitinfo.json
          {
              "commitHash": "$(git rev-parse --short HEAD)",
              "commitTimestamp": "$(date -u -d "$(git log -1 --format=%cI)" +'%Y-%m-%dT%H:%M:%SZ')",
              "branchName": "$(git rev-parse --abbrev-ref HEAD)",
              "tagName": "$(git describe --tags --abbrev=0 2>/dev/null)",
              "buildTimestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          }
          EOT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        if: ${{ secrets.DOCKERHUB_USERNAME != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta Backend
        id: metabackend
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_BACKEND }}
            ${{ env.DOCKERHUB_IMAGE_BACKEND }}
          labels: |
            org.opencontainers.image.title=rc-chat-backend
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=beta,enable=${{ github.ref == 'refs/heads/beta' }}
            type=sha

      - name: Docker meta Frontend
        id: metafrontend
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_FRONTEND }}
            ${{ env.DOCKERHUB_IMAGE_FRONTEND }}
          labels: |
            org.opencontainers.image.title=rc-chat-frontend
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=beta,enable=${{ github.ref == 'refs/heads/beta' }}
            type=sha

      - name: Build and push backend Docker image
        id: backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metabackend.outputs.tags }}
          labels: ${{ steps.metabackend.outputs.labels }}

      - name: Build and push frontend Docker image
        id: frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metafrontend.outputs.tags }}
          labels: ${{ steps.metafrontend.outputs.labels }}
